# Generated by Django 3.2.1 on 2024-03-15 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_courses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
