# Generated by Django 3.2.1 on 2024-02-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100, unique=True)),
                ('course_difficulty', models.CharField(default='Beginner', max_length=100)),
                ('course_duration', models.CharField(default='1', max_length=100)),
                ('course_details', models.JSONField(default=dict)),
            ],
        ),
    ]
