# Generated by Django 4.2.5 on 2023-10-29 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100, unique=True)),
                ('course_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CourseResources',
            fields=[
                ('course_resource_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('course_resource_name', models.CharField(max_length=100)),
                ('course_resource_description', models.CharField(max_length=1000)),
                ('course_resource_link', models.CharField(max_length=1000)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPT_API.courses')),
            ],
        ),
    ]
