# Generated by Django 4.2.5 on 2023-11-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100, unique=True)),
                ('course_difficulty', models.CharField(default='Beginner', max_length=100)),
                ('course_duration', models.CharField(default='1', max_length=100)),
                ('course_description', models.CharField(max_length=1000)),
            ],
        ),
    ]
