# Generated by Django 4.2.5 on 2024-02-24 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPT_API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='course_schedule',
            new_name='course_details',
        ),
    ]
