# Generated by Django 4.2.5 on 2023-11-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPT_API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='ne_field',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
