# Generated by Django 3.2.1 on 2024-03-15 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPT_API', '0002_courses_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
