# Generated by Django 4.2.5 on 2023-12-05 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPT_API', '0003_remove_courses_ne_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='course_description',
            new_name='course_schedule',
        ),
    ]
