# Generated by Django 4.2.5 on 2023-12-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPT_API', '0006_alter_courses_course_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_schedule',
            field=models.JSONField(default=dict),
        ),
    ]
