# Generated by Django 4.2.5 on 2024-01-31 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPT_API', '0007_alter_courses_course_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='course_schedule',
            new_name='course_details',
        ),
    ]
