# Generated by Django 3.2.1 on 2024-03-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPT_API', '0008_alter_courses_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_summary',
            field=models.TextField(default='This is a course'),
        ),
    ]
