# Generated by Django 3.2.1 on 2024-03-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPT_API', '0011_alter_courses_course_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_skills',
            field=models.CharField(default='Python', max_length=100),
        ),
    ]
