# Generated by Django 3.2.1 on 2024-03-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPT_API', '0012_courses_course_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
