# Generated by Django 3.2.1 on 2024-03-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPT_API', '0014_alter_courses_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
