# Generated by Django 3.2.1 on 2024-03-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPT_API', '0017_auto_20240325_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourses',
            name='completed',
            field=models.JSONField(default=dict),
        ),
        migrations.RemoveField(
            model_name='usercourses',
            name='courses',
        ),
        migrations.AddField(
            model_name='usercourses',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='GPT_API.Courses'),
        ),
    ]
